Feat/31 user grpc endpoints
krok-o/krok pull request #34
Opened 2021-01-18 22:31 UTC by speza

Feat/31 user grpc endpoints - #31 

Implemented all the user api key endpoints (hoping I've not broken one... its a lot of code).

2021-01-19 14:06 UTC, Skarlso requested changes
One things that needs to be changed.. 

Now that we are using GRPC we have a functionality which we can exploit on the generated content and these are `Get*`s. Please use them whenever accessing something on a GRPC resource that it coming back from a call. They prevent `nil` access of things.

So like, if you look at the resource, you'll see that there is a Get* generated for everything which first check if the said resource in nil.

This makes it so that we can actually chain stuff without worrying about nil errors.
So like, GetItems()... GetID()... request.UserId.Value -> especially this would throw a nil panic if UserId would be nil somehow and we miss to check it. Where as request.GetUserId().GetValue() would not panic.

2021-01-19 16:22 UTC, speza commented on proto/user/v1/user.proto
> +  repeated APIKey list = 1;
Yeah good point. List sounds awful :joy:

2021-01-19 16:22 UTC, speza commented on pkg/krok/providers/service/user_apikey.go
> +	storer providers.APIKeysStorer,
Yeah I can do this, I should have anyway as its the pattern elsewhere!

2021-01-20 06:08 UTC, Skarlso approved these changes
LGTM please főz the log errs to debug.err then merge. 😊🙏

2021-01-20 07:36 UTC, merged